package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Canvas = 0;
  public static final int Circle = 1;
  public static final int Color = 2;
  public static final int ColorReference = 3;
  public static final int Shape = 4;
  public static final int Square = 5;
  public static final int Triangle = 6;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xfc26dc03fc41caL, 0xae81976686e2680eL);
    builder.put(0x6802da97a67062deL, Canvas);
    builder.put(0x6802da97a67062c3L, Circle);
    builder.put(0x6802da97a6732b9dL, Color);
    builder.put(0x6802da97a674e34eL, ColorReference);
    builder.put(0x6802da97a67062bfL, Shape);
    builder.put(0x6802da97a67062d0L, Square);
    builder.put(0x6dc7918e6bf1f7d3L, Triangle);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
