package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptCircle = createDescriptorForCircle();
  /*package*/ final ConceptDescriptor myConceptColor = createDescriptorForColor();
  /*package*/ final ConceptDescriptor myConceptColorReference = createDescriptorForColorReference();
  /*package*/ final ConceptDescriptor myConceptShape = createDescriptorForShape();
  /*package*/ final ConceptDescriptor myConceptSquare = createDescriptorForSquare();
  /*package*/ final ConceptDescriptor myConceptTriangle = createDescriptorForTriangle();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, "jetbrains.mps.execution.util");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCanvas, myConceptCircle, myConceptColor, myConceptColorReference, myConceptShape, myConceptSquare, myConceptTriangle);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Canvas:
        return myConceptCanvas;
      case LanguageConceptSwitch.Circle:
        return myConceptCircle;
      case LanguageConceptSwitch.Color:
        return myConceptColor;
      case LanguageConceptSwitch.ColorReference:
        return myConceptColorReference;
      case LanguageConceptSwitch.Shape:
        return myConceptShape;
      case LanguageConceptSwitch.Square:
        return myConceptSquare;
      case LanguageConceptSwitch.Triangle:
        return myConceptTriangle;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCanvas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Canvas", 0xfc26dc03fc41caL, 0xae81976686e2680eL, 0x6802da97a67062deL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:9303dad0-504f-42a6-bfc1-f1cc08ce8969(Shapes.structure)/7494793074765226718");
    b.version(3);
    b.aggregate("shapes", 0x6802da97a67062e4L).target(0xfc26dc03fc41caL, 0xae81976686e2680eL, 0x6802da97a67062bfL).optional(true).ordered(true).multiple(true).origin("7494793074765226724").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCircle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Circle", 0xfc26dc03fc41caL, 0xae81976686e2680eL, 0x6802da97a67062c3L);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0xfc26dc03fc41caL, 0xae81976686e2680eL, 0x6802da97a67062bfL);
    b.origin("r:9303dad0-504f-42a6-bfc1-f1cc08ce8969(Shapes.structure)/7494793074765226691");
    b.version(3);
    b.property("x", 0x6802da97a67062c9L).type(PrimitiveTypeId.INTEGER).origin("7494793074765226697").done();
    b.property("y", 0x6802da97a67062cbL).type(PrimitiveTypeId.INTEGER).origin("7494793074765226699").done();
    b.property("radius", 0x6802da97a67062ccL).type(PrimitiveTypeId.INTEGER).origin("7494793074765226700").done();
    b.alias("circle");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Color", 0xfc26dc03fc41caL, 0xae81976686e2680eL, 0x6802da97a6732b9dL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:9303dad0-504f-42a6-bfc1-f1cc08ce8969(Shapes.structure)/7494793074765409181");
    b.version(3);
    b.alias("color");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColorReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "ColorReference", 0xfc26dc03fc41caL, 0xae81976686e2680eL, 0x6802da97a674e34eL);
    b.class_(false, false, false);
    b.origin("r:9303dad0-504f-42a6-bfc1-f1cc08ce8969(Shapes.structure)/7494793074765521742");
    b.version(3);
    b.associate("target", 0x6802da97a674e352L).target(0xfc26dc03fc41caL, 0xae81976686e2680eL, 0x6802da97a6732b9dL).optional(false).origin("7494793074765521746").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShape() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Shape", 0xfc26dc03fc41caL, 0xae81976686e2680eL, 0x6802da97a67062bfL);
    b.class_(false, true, false);
    b.origin("r:9303dad0-504f-42a6-bfc1-f1cc08ce8969(Shapes.structure)/7494793074765226687");
    b.version(3);
    b.aggregate("color", 0x6802da97a674e370L).target(0xfc26dc03fc41caL, 0xae81976686e2680eL, 0x6802da97a674e34eL).optional(false).ordered(true).multiple(false).origin("7494793074765521776").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSquare() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Square", 0xfc26dc03fc41caL, 0xae81976686e2680eL, 0x6802da97a67062d0L);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0xfc26dc03fc41caL, 0xae81976686e2680eL, 0x6802da97a67062bfL);
    b.origin("r:9303dad0-504f-42a6-bfc1-f1cc08ce8969(Shapes.structure)/7494793074765226704");
    b.version(3);
    b.property("upperLeftX", 0x6802da97a67062d4L).type(PrimitiveTypeId.INTEGER).origin("7494793074765226708").done();
    b.property("upperLeftY", 0x6802da97a67062d7L).type(PrimitiveTypeId.INTEGER).origin("7494793074765226711").done();
    b.property("size", 0x6802da97a67062daL).type(PrimitiveTypeId.INTEGER).origin("7494793074765226714").done();
    b.alias("square");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTriangle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Triangle", 0xfc26dc03fc41caL, 0xae81976686e2680eL, 0x6dc7918e6bf1f7d3L);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0xfc26dc03fc41caL, 0xae81976686e2680eL, 0x6802da97a67062bfL);
    b.origin("r:9303dad0-504f-42a6-bfc1-f1cc08ce8969(Shapes.structure)/7910451311381968851");
    b.version(3);
    b.property("side", 0x6dc7918e6bf1f862L).type(PrimitiveTypeId.INTEGER).origin("7910451311381968994").done();
    b.property("rotationDeg", 0x6dc7918e6bf1f875L).type(PrimitiveTypeId.INTEGER).origin("7910451311381969013").done();
    b.property("x", 0x6dc7918e6bf2ed03L).type(PrimitiveTypeId.INTEGER).origin("7910451311382031619").done();
    b.property("y", 0x6dc7918e6bf2ed1cL).type(PrimitiveTypeId.INTEGER).origin("7910451311382031644").done();
    b.alias("triangle");
    return b.create();
  }
}
